spring.application.name=project

# =========================================
# POSTGRESQL DATABASE
# =========================================

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# =========================================
# HIKARI CONNECTION POOL
# =========================================

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.max-lifetime=300000


# =========================================
# JPA / HIBERNATE
# =========================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true


# =========================================
# JWT
# =========================================

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}


# =========================================
# SERVER
# =========================================

server.port=8080
server.address=0.0.0.0